//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A network transport system that transfers the data between several
 *                 nodes.
 * 
 * <p>Java class for BusType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="BusType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Message" type="{http://kayak.2codeornot2code.org/1.0}MessageType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="baudrate" default="500000">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *             <minInclusive value="5000"/>
 *             <maxInclusive value="1000000"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusType", propOrder = {
    "message"
})
public class BusType {

    @XmlElement(name = "Message")
    protected List<MessageType> message;
    /**
     * Human-readable name of the bus network (e.g.
     *                     "Comfort").
     * 
     */
    @XmlAttribute(name = "name", required = true)
    protected String name;
    /**
     * Nominal data transfer rate in baud (e.g. 500000, 125000, 100000 or
     *                     83333).
     * 
     */
    @XmlAttribute(name = "baudrate")
    protected Integer baudrate;

    /**
     * Gets the value of the message property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageType }
     * </p>
     * 
     * 
     * @return
     *     The value of the message property.
     */
    public List<MessageType> getMessage() {
        if (message == null) {
            message = new ArrayList<>();
        }
        return this.message;
    }

    /**
     * Human-readable name of the bus network (e.g.
     *                     "Comfort").
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Nominal data transfer rate in baud (e.g. 500000, 125000, 100000 or
     *                     83333).
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getBaudrate() {
        if (baudrate == null) {
            return  500000;
        } else {
            return baudrate;
        }
    }

    /**
     * Sets the value of the baudrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getBaudrate()
     */
    public void setBaudrate(Integer value) {
        this.baudrate = value;
    }

}
