//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * Describes the scope of application e.g. the target vehicle or
 *                 controlled device.
 * 
 * <p>Java class for DocumentType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DocumentType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       <attribute name="version" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       <attribute name="author" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       <attribute name="company" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       <attribute name="date" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentType", propOrder = {
    "content"
})
public class DocumentType {

    /**
     * Describes the scope of application e.g. the target vehicle or
     *                 controlled device.
     * 
     */
    @XmlValue
    protected String content;
    /**
     * The name of the network definition document.
     * 
     */
    @XmlAttribute(name = "name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    /**
     * The version of the network definition document.
     * 
     */
    @XmlAttribute(name = "version")
    @XmlSchemaType(name = "anySimpleType")
    protected String version;
    /**
     * The owner or author of the network definition
     *                     document.
     * 
     */
    @XmlAttribute(name = "author")
    @XmlSchemaType(name = "anySimpleType")
    protected String author;
    /**
     * The owner company of the network definition
     *                     document.
     * 
     */
    @XmlAttribute(name = "company")
    @XmlSchemaType(name = "anySimpleType")
    protected String company;
    /**
     * The release date of this version of the network definition
     *                     document.
     * 
     */
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "anySimpleType")
    protected String date;

    /**
     * Describes the scope of application e.g. the target vehicle or
     *                 controlled device.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getContent()
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * The name of the network definition document.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getName()
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * The version of the network definition document.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getVersion()
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * The owner or author of the network definition
     *                     document.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAuthor()
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * The owner company of the network definition
     *                     document.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCompany()
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * The release date of this version of the network definition
     *                     document.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDate()
     */
    public void setDate(String value) {
        this.date = value;
    }

}
