//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A set of label and label groups. Each label describes the meaning of a
 *                 single raw value by an alias name. A single value can only belong to a one label or
 *                 label group.
 * 
 * <p>Java class for LabelSetType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="LabelSetType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="Label" type="{http://kayak.2codeornot2code.org/1.0}LabelType" minOccurs="0"/>
 *         <element name="LabelGroup" type="{http://kayak.2codeornot2code.org/1.0}LabelGroupType" minOccurs="0"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelSetType", propOrder = {
    "labelOrLabelGroup"
})
public class LabelSetType {

    @XmlElements({
        @XmlElement(name = "Label", type = LabelType.class),
        @XmlElement(name = "LabelGroup", type = LabelGroupType.class)
    })
    protected List<BasicLabelType> labelOrLabelGroup;

    /**
     * Gets the value of the labelOrLabelGroup property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelOrLabelGroup property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLabelOrLabelGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelGroupType }
     * {@link LabelType }
     * </p>
     * 
     * 
     * @return
     *     The value of the labelOrLabelGroup property.
     */
    public List<BasicLabelType> getLabelOrLabelGroup() {
        if (labelOrLabelGroup == null) {
            labelOrLabelGroup = new ArrayList<>();
        }
        return this.labelOrLabelGroup;
    }

}
