//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Descriptive name for a sequence of adjacent values.
 * 
 * <p>Java class for LabelGroupType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="LabelGroupType">
 *   <complexContent>
 *     <extension base="{http://kayak.2codeornot2code.org/1.0}BasicLabelType">
 *       <attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       <attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelGroupType")
public class LabelGroupType
    extends BasicLabelType
{

    /**
     * Signal raw value the label group is starting
     *                             with.
     * 
     */
    @XmlAttribute(name = "from", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger from;
    /**
     * Signal raw value the label group is ending
     *                             with.
     * 
     */
    @XmlAttribute(name = "to", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger to;

    /**
     * Signal raw value the label group is starting
     *                             with.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getFrom()
     */
    public void setFrom(BigInteger value) {
        this.from = value;
    }

    /**
     * Signal raw value the label group is ending
     *                             with.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getTo()
     */
    public void setTo(BigInteger value) {
        this.to = value;
    }

}
