//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.01 at 10:58:48 AM NZDT 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A datagram that is used to transport payload data along the bus
 *                 network.
 * 
 * <p>Java class for MessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Notes" type="{http://kayak.2codeornot2code.org/1.0}NotesType" minOccurs="0"/>
 *         &lt;element name="Producer" type="{http://kayak.2codeornot2code.org/1.0}ProducerType" minOccurs="0"/>
 *         &lt;element name="Multiplex" type="{http://kayak.2codeornot2code.org/1.0}MultiplexType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Signal" type="{http://kayak.2codeornot2code.org/1.0}SignalType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="0x[A-F0-9]+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length" default="auto">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="auto"/>
 *             &lt;enumeration value="0"/>
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="7"/>
 *             &lt;enumeration value="8"/>
 *             &lt;enumeration value="12"/>
 *             &lt;enumeration value="16"/>
 *             &lt;enumeration value="20"/>
 *             &lt;enumeration value="24"/>
 *             &lt;enumeration value="32"/>
 *             &lt;enumeration value="48"/>
 *             &lt;enumeration value="64"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="interval" default="0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="60000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="triggered" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="count" default="0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *             &lt;minInclusive value="0"/>
 *             &lt;maxInclusive value="1000000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="format" default="standard">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="standard"/>
 *             &lt;enumeration value="extended"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="fd" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="bitrateswitch" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="remote" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageType", propOrder = {
    "notes",
    "producer",
    "multiplex",
    "signal"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class MessageType {

    @XmlElement(name = "Notes")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String notes;
    @XmlElement(name = "Producer")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ProducerType producer;
    @XmlElement(name = "Multiplex")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<MultiplexType> multiplex;
    @XmlElement(name = "Signal")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<SignalType> signal;
    @XmlAttribute(name = "id", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String id;
    @XmlAttribute(name = "name", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String name;
    @XmlAttribute(name = "length")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String length;
    @XmlAttribute(name = "interval")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Integer interval;
    @XmlAttribute(name = "triggered")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Boolean triggered;
    @XmlAttribute(name = "count")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Integer count;
    @XmlAttribute(name = "format")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String format;
    @XmlAttribute(name = "fd")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Boolean fd;
    @XmlAttribute(name = "bitrateswitch")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Boolean bitrateswitch;
    @XmlAttribute(name = "remote")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Boolean remote;

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link ProducerType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ProducerType getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducerType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setProducer(ProducerType value) {
        this.producer = value;
    }

    /**
     * Gets the value of the multiplex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiplex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultiplex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultiplexType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<MultiplexType> getMultiplex() {
        if (multiplex == null) {
            multiplex = new ArrayList<MultiplexType>();
        }
        return this.multiplex;
    }

    /**
     * Gets the value of the signal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignalType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<SignalType> getSignal() {
        if (signal == null) {
            signal = new ArrayList<SignalType>();
        }
        return this.signal;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getLength() {
        if (length == null) {
            return "auto";
        } else {
            return length;
        }
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public int getInterval() {
        if (interval == null) {
            return  0;
        } else {
            return interval;
        }
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setInterval(Integer value) {
        this.interval = value;
    }

    /**
     * Gets the value of the triggered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isTriggered() {
        if (triggered == null) {
            return false;
        } else {
            return triggered;
        }
    }

    /**
     * Sets the value of the triggered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setTriggered(Boolean value) {
        this.triggered = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public int getCount() {
        if (count == null) {
            return  0;
        } else {
            return count;
        }
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setCount(Integer value) {
        this.count = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getFormat() {
        if (format == null) {
            return "standard";
        } else {
            return format;
        }
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the fd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isFd() {
        if (fd == null) {
            return false;
        } else {
            return fd;
        }
    }

    /**
     * Sets the value of the fd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setFd(Boolean value) {
        this.fd = value;
    }

    /**
     * Gets the value of the bitrateswitch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isBitrateswitch() {
        if (bitrateswitch == null) {
            return false;
        } else {
            return bitrateswitch;
        }
    }

    /**
     * Sets the value of the bitrateswitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setBitrateswitch(Boolean value) {
        this.bitrateswitch = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isRemote() {
        if (remote == null) {
            return false;
        } else {
            return remote;
        }
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setRemote(Boolean value) {
        this.remote = value;
    }

}
