//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A looping counter to make a group of signals (MuxGroup) alternately
 *                 active at a time.
 * 
 * <p>Java class for MultiplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MultiplexType">
 *   <complexContent>
 *     <extension base="{http://kayak.2codeornot2code.org/1.0}BasicSignalType">
 *       <sequence>
 *         <element name="MuxGroup" type="{http://kayak.2codeornot2code.org/1.0}MuxGroupType" maxOccurs="unbounded"/>
 *         <element name="Notes" type="{http://kayak.2codeornot2code.org/1.0}NotesType" minOccurs="0"/>
 *         <element name="Consumer" type="{http://kayak.2codeornot2code.org/1.0}ConsumerType" minOccurs="0"/>
 *         <element name="Value" type="{http://kayak.2codeornot2code.org/1.0}ValueType" minOccurs="0"/>
 *         <element name="LabelSet" type="{http://kayak.2codeornot2code.org/1.0}LabelSetType" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiplexType", propOrder = {
    "muxGroup",
    "notes",
    "consumer",
    "value",
    "labelSet"
})
public class MultiplexType
    extends BasicSignalType
{

    @XmlElement(name = "MuxGroup", required = true)
    protected List<MuxGroupType> muxGroup;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "Consumer")
    protected ConsumerType consumer;
    @XmlElement(name = "Value")
    protected ValueType value;
    @XmlElement(name = "LabelSet")
    protected LabelSetType labelSet;

    /**
     * Gets the value of the muxGroup property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the muxGroup property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMuxGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MuxGroupType }
     * </p>
     * 
     * 
     * @return
     *     The value of the muxGroup property.
     */
    public List<MuxGroupType> getMuxGroup() {
        if (muxGroup == null) {
            muxGroup = new ArrayList<>();
        }
        return this.muxGroup;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the consumer property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerType }
     *     
     */
    public ConsumerType getConsumer() {
        return consumer;
    }

    /**
     * Sets the value of the consumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerType }
     *     
     */
    public void setConsumer(ConsumerType value) {
        this.consumer = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link ValueType }
     *     
     */
    public ValueType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueType }
     *     
     */
    public void setValue(ValueType value) {
        this.value = value;
    }

    /**
     * Gets the value of the labelSet property.
     * 
     * @return
     *     possible object is
     *     {@link LabelSetType }
     *     
     */
    public LabelSetType getLabelSet() {
        return labelSet;
    }

    /**
     * Sets the value of the labelSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelSetType }
     *     
     */
    public void setLabelSet(LabelSetType value) {
        this.labelSet = value;
    }

}
