//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A group of signals that is just valid when the count value of the
 *                 group matches with the looping counter (Multiplex).
 * 
 * <p>Java class for MuxGroupType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MuxGroupType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Signal" type="{http://kayak.2codeornot2code.org/1.0}SignalType" maxOccurs="unbounded"/>
 *       </sequence>
 *       <attribute name="count" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *             <minInclusive value="0"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MuxGroupType", propOrder = {
    "signal"
})
public class MuxGroupType {

    @XmlElement(name = "Signal", required = true)
    protected List<SignalType> signal;
    /**
     * Count value of the Multiplex when the signals of this group become
     *                     valid.
     * 
     */
    @XmlAttribute(name = "count", required = true)
    protected long count;

    /**
     * Gets the value of the signal property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signal property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getSignal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignalType }
     * </p>
     * 
     * 
     * @return
     *     The value of the signal property.
     */
    public List<SignalType> getSignal() {
        if (signal == null) {
            signal = new ArrayList<>();
        }
        return this.signal;
    }

    /**
     * Count value of the Multiplex when the signals of this group become
     *                     valid.
     * 
     */
    public long getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(long value) {
        this.count = value;
    }

}
