//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="NodeType">
 *   <complexContent>
 *     <extension base="{http://kayak.2codeornot2code.org/1.0}NodeType">
 *       <redefine>
 *         <complexType name="NodeType">
 *           <complexContent>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               <sequence maxOccurs="unbounded" minOccurs="0">
 *                 <element name="Var" type="{http://kayak.2codeornot2code.org/1.0}VarType"/>
 *               </sequence>
 *               <attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               <attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *             </restriction>
 *           </complexContent>
 *         </complexType>
 *       </redefine>
 *       <sequence>
 *         <element name="Expression" type="{urn:solarnetwork:datum:1.0}PropertyExpression" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Metadata" type="{urn:solarnetwork:datum:1.0}MetadataProperty" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}source-id use="required""/>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}publish-interval"/>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}network-service-name default="Canbus Port""/>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeType", propOrder = {
    "expression",
    "metadata"
})
public class NodeType
    extends OriginalNodeType
{

    /**
     * Property expressions to apply to datum.
     * 
     */
    @XmlElement(name = "Expression")
    protected List<PropertyExpression> expression;
    /**
     * Property metadata to include.
     * 
     */
    @XmlElement(name = "Metadata")
    protected List<MetadataProperty> metadata;
    /**
     * A SolarNetwork Source ID to associate with datum
     *                                 collected for this node.
     * 
     */
    @XmlAttribute(name = "source-id", namespace = "urn:solarnetwork:datum:1.0", required = true)
    protected String sourceId;
    /**
     * The frequency at which to publish datum for this node,
     *                                 in milliseconds.
     * 
     */
    @XmlAttribute(name = "publish-interval", namespace = "urn:solarnetwork:datum:1.0")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger publishInterval;
    /**
     * The service name of the CAN Bus Connection component
     *                                 that provides the connection to the physical CAN bus
     *                                 network.
     * 
     */
    @XmlAttribute(name = "network-service-name", namespace = "urn:solarnetwork:datum:1.0")
    protected String networkServiceName;

    /**
     * Property expressions to apply to datum.
     * 
     * Gets the value of the expression property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expression property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyExpression }
     * </p>
     * 
     * 
     * @return
     *     The value of the expression property.
     */
    public List<PropertyExpression> getExpression() {
        if (expression == null) {
            expression = new ArrayList<>();
        }
        return this.expression;
    }

    /**
     * Property metadata to include.
     * 
     * Gets the value of the metadata property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataProperty }
     * </p>
     * 
     * 
     * @return
     *     The value of the metadata property.
     */
    public List<MetadataProperty> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<>();
        }
        return this.metadata;
    }

    /**
     * A SolarNetwork Source ID to associate with datum
     *                                 collected for this node.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * Sets the value of the sourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSourceId()
     */
    public void setSourceId(String value) {
        this.sourceId = value;
    }

    /**
     * The frequency at which to publish datum for this node,
     *                                 in milliseconds.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPublishInterval() {
        if (publishInterval == null) {
            return new BigInteger("60000");
        } else {
            return publishInterval;
        }
    }

    /**
     * Sets the value of the publishInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getPublishInterval()
     */
    public void setPublishInterval(BigInteger value) {
        this.publishInterval = value;
    }

    /**
     * The service name of the CAN Bus Connection component
     *                                 that provides the connection to the physical CAN bus
     *                                 network.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkServiceName() {
        if (networkServiceName == null) {
            return "Canbus Port";
        } else {
            return networkServiceName;
        }
    }

    /**
     * Sets the value of the networkServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNetworkServiceName()
     */
    public void setNetworkServiceName(String value) {
        this.networkServiceName = value;
    }

}
