//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.19 at 08:11:34 AM NZDT 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://kayak.2codeornot2code.org/1.0}NodeType">
 *       &lt;redefine>
 *         &lt;complexType name="NodeType">
 *           &lt;complexContent>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                 &lt;element name="Var" type="{http://kayak.2codeornot2code.org/1.0}VarType"/>
 *               &lt;/sequence>
 *               &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *             &lt;/restriction>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}source-id use="required""/>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}publish-interval"/>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}network-service-name default="Canbus Port""/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeType")
public class NodeType
    extends OriginalNodeType
{

    @XmlAttribute(name = "source-id", namespace = "urn:solarnetwork:datum:1.0", required = true)
    protected String sourceId;
    @XmlAttribute(name = "publish-interval", namespace = "urn:solarnetwork:datum:1.0")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger publishInterval;
    @XmlAttribute(name = "network-service-name", namespace = "urn:solarnetwork:datum:1.0")
    protected String networkServiceName;

    /**
     * A SolarNetwork Source ID to associate with datum
     *                                 collected for this node.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * Sets the value of the sourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceId(String value) {
        this.sourceId = value;
    }

    /**
     * The frequency at which to publish datum for this node,
     *                                 in milliseconds.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPublishInterval() {
        if (publishInterval == null) {
            return new BigInteger("60000");
        } else {
            return publishInterval;
        }
    }

    /**
     * Sets the value of the publishInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPublishInterval(BigInteger value) {
        this.publishInterval = value;
    }

    /**
     * The service name of the CAN Bus Connection component
     *                                 that provides the connection to the physical CAN bus
     *                                 network.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkServiceName() {
        if (networkServiceName == null) {
            return "Canbus Port";
        } else {
            return networkServiceName;
        }
    }

    /**
     * Sets the value of the networkServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkServiceName(String value) {
        this.networkServiceName = value;
    }

}
