//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.01 at 10:58:48 AM NZDT 
//


package net.solarnetwork.node.io.canbus.kcd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.solarnetwork.node.io.canbus.kcd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NetworkDefinition_QNAME = new QName("http://kayak.2codeornot2code.org/1.0", "NetworkDefinition");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.solarnetwork.node.io.canbus.kcd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NetworkDefinitionType }
     * 
     */
    public NetworkDefinitionType createNetworkDefinitionType() {
        return new NetworkDefinitionType();
    }

    /**
     * Create an instance of {@link LabelSetType }
     * 
     */
    public LabelSetType createLabelSetType() {
        return new LabelSetType();
    }

    /**
     * Create an instance of {@link BusType }
     * 
     */
    public BusType createBusType() {
        return new BusType();
    }

    /**
     * Create an instance of {@link SignalType }
     * 
     */
    public SignalType createSignalType() {
        return new SignalType();
    }

    /**
     * Create an instance of {@link ProducerType }
     * 
     */
    public ProducerType createProducerType() {
        return new ProducerType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link MuxGroupType }
     * 
     */
    public MuxGroupType createMuxGroupType() {
        return new MuxGroupType();
    }

    /**
     * Create an instance of {@link LabelGroupType }
     * 
     */
    public LabelGroupType createLabelGroupType() {
        return new LabelGroupType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link MultiplexType }
     * 
     */
    public MultiplexType createMultiplexType() {
        return new MultiplexType();
    }

    /**
     * Create an instance of {@link VarType }
     * 
     */
    public VarType createVarType() {
        return new VarType();
    }

    /**
     * Create an instance of {@link BasicLabelType }
     * 
     */
    public BasicLabelType createBasicLabelType() {
        return new BasicLabelType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link ConsumerType }
     * 
     */
    public ConsumerType createConsumerType() {
        return new ConsumerType();
    }

    /**
     * Create an instance of {@link BasicSignalType }
     * 
     */
    public BasicSignalType createBasicSignalType() {
        return new BasicSignalType();
    }

    /**
     * Create an instance of {@link NodeRefType }
     * 
     */
    public NodeRefType createNodeRefType() {
        return new NodeRefType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link OriginalNodeType }
     * 
     */
    public OriginalNodeType createOriginalNodeType() {
        return new OriginalNodeType();
    }

    /**
     * Create an instance of {@link OriginalSignalType }
     * 
     */
    public OriginalSignalType createOriginalSignalType() {
        return new OriginalSignalType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kayak.2codeornot2code.org/1.0", name = "NetworkDefinition")
    public JAXBElement<NetworkDefinitionType> createNetworkDefinition(NetworkDefinitionType value) {
        return new JAXBElement<NetworkDefinitionType>(_NetworkDefinition_QNAME, NetworkDefinitionType.class, null, value);
    }

}
