//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.solarnetwork.node.io.canbus.kcd package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _NetworkDefinition_QNAME = new QName("http://kayak.2codeornot2code.org/1.0", "NetworkDefinition");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.solarnetwork.node.io.canbus.kcd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NetworkDefinitionType }
     * 
     * @return
     *     the new instance of {@link NetworkDefinitionType }
     */
    public NetworkDefinitionType createNetworkDefinitionType() {
        return new NetworkDefinitionType();
    }

    /**
     * Create an instance of {@link BusType }
     * 
     * @return
     *     the new instance of {@link BusType }
     */
    public BusType createBusType() {
        return new BusType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     * @return
     *     the new instance of {@link MessageType }
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link MultiplexType }
     * 
     * @return
     *     the new instance of {@link MultiplexType }
     */
    public MultiplexType createMultiplexType() {
        return new MultiplexType();
    }

    /**
     * Create an instance of {@link MuxGroupType }
     * 
     * @return
     *     the new instance of {@link MuxGroupType }
     */
    public MuxGroupType createMuxGroupType() {
        return new MuxGroupType();
    }

    /**
     * Create an instance of {@link LabelSetType }
     * 
     * @return
     *     the new instance of {@link LabelSetType }
     */
    public LabelSetType createLabelSetType() {
        return new LabelSetType();
    }

    /**
     * Create an instance of {@link SignalType }
     * 
     * @return
     *     the new instance of {@link SignalType }
     */
    public SignalType createSignalType() {
        return new SignalType();
    }

    /**
     * Create an instance of {@link ProducerType }
     * 
     * @return
     *     the new instance of {@link ProducerType }
     */
    public ProducerType createProducerType() {
        return new ProducerType();
    }

    /**
     * Create an instance of {@link ConsumerType }
     * 
     * @return
     *     the new instance of {@link ConsumerType }
     */
    public ConsumerType createConsumerType() {
        return new ConsumerType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     * @return
     *     the new instance of {@link ValueType }
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     * @return
     *     the new instance of {@link LabelType }
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link LabelGroupType }
     * 
     * @return
     *     the new instance of {@link LabelGroupType }
     */
    public LabelGroupType createLabelGroupType() {
        return new LabelGroupType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     * @return
     *     the new instance of {@link NodeType }
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link NodeRefType }
     * 
     * @return
     *     the new instance of {@link NodeRefType }
     */
    public NodeRefType createNodeRefType() {
        return new NodeRefType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     * @return
     *     the new instance of {@link DocumentType }
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link VarType }
     * 
     * @return
     *     the new instance of {@link VarType }
     */
    public VarType createVarType() {
        return new VarType();
    }

    /**
     * Create an instance of {@link BasicLabelType }
     * 
     * @return
     *     the new instance of {@link BasicLabelType }
     */
    public BasicLabelType createBasicLabelType() {
        return new BasicLabelType();
    }

    /**
     * Create an instance of {@link BasicSignalType }
     * 
     * @return
     *     the new instance of {@link BasicSignalType }
     */
    public BasicSignalType createBasicSignalType() {
        return new BasicSignalType();
    }

    /**
     * Create an instance of {@link LocalizedName }
     * 
     * @return
     *     the new instance of {@link LocalizedName }
     */
    public LocalizedName createLocalizedName() {
        return new LocalizedName();
    }

    /**
     * Create an instance of {@link PropertyExpression }
     * 
     * @return
     *     the new instance of {@link PropertyExpression }
     */
    public PropertyExpression createPropertyExpression() {
        return new PropertyExpression();
    }

    /**
     * Create an instance of {@link MetadataProperty }
     * 
     * @return
     *     the new instance of {@link MetadataProperty }
     */
    public MetadataProperty createMetadataProperty() {
        return new MetadataProperty();
    }

    /**
     * Create an instance of {@link OriginalNodeType }
     * 
     * @return
     *     the new instance of {@link OriginalNodeType }
     */
    public OriginalNodeType createOriginalNodeType() {
        return new OriginalNodeType();
    }

    /**
     * Create an instance of {@link OriginalValueType }
     * 
     * @return
     *     the new instance of {@link OriginalValueType }
     */
    public OriginalValueType createOriginalValueType() {
        return new OriginalValueType();
    }

    /**
     * Create an instance of {@link OriginalSignalType }
     * 
     * @return
     *     the new instance of {@link OriginalSignalType }
     */
    public OriginalSignalType createOriginalSignalType() {
        return new OriginalSignalType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkDefinitionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NetworkDefinitionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://kayak.2codeornot2code.org/1.0", name = "NetworkDefinition")
    public JAXBElement<NetworkDefinitionType> createNetworkDefinition(NetworkDefinitionType value) {
        return new JAXBElement<>(_NetworkDefinition_QNAME, NetworkDefinitionType.class, null, value);
    }

}
