//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A discrete part of information contained in the payload of a
 *                 message.
 * 
 * <p>Java class for SignalType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="SignalType">
 *   <complexContent>
 *     <extension base="{http://kayak.2codeornot2code.org/1.0}BasicSignalType">
 *       <sequence>
 *         <element name="Notes" type="{http://kayak.2codeornot2code.org/1.0}NotesType" minOccurs="0"/>
 *         <element name="Consumer" type="{http://kayak.2codeornot2code.org/1.0}ConsumerType" minOccurs="0"/>
 *         <element name="Value" type="{http://kayak.2codeornot2code.org/1.0}ValueType" minOccurs="0"/>
 *         <element name="LabelSet" type="{http://kayak.2codeornot2code.org/1.0}LabelSetType" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notes",
    "consumer",
    "value",
    "labelSet"
})
@XmlSeeAlso({
    SignalType.class
})
public class OriginalSignalType
    extends BasicSignalType
{

    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "Consumer")
    protected ConsumerType consumer;
    @XmlElement(name = "Value")
    protected ValueType value;
    @XmlElement(name = "LabelSet")
    protected LabelSetType labelSet;

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the consumer property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerType }
     *     
     */
    public ConsumerType getConsumer() {
        return consumer;
    }

    /**
     * Sets the value of the consumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerType }
     *     
     */
    public void setConsumer(ConsumerType value) {
        this.consumer = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link ValueType }
     *     
     */
    public ValueType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueType }
     *     
     */
    public void setValue(ValueType value) {
        this.value = value;
    }

    /**
     * Gets the value of the labelSet property.
     * 
     * @return
     *     possible object is
     *     {@link LabelSetType }
     *     
     */
    public LabelSetType getLabelSet() {
        return labelSet;
    }

    /**
     * Sets the value of the labelSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelSetType }
     *     
     */
    public void setLabelSet(LabelSetType value) {
        this.labelSet = value;
    }

}
