//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.08 at 06:24:10 PM NZST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kayak.2codeornot2code.org/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.solarnetwork.node.io.canbus.kcd;
