//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A datum property derived from an expression.
 * 
 * <p>Java class for PropertyExpression complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="PropertyExpression">
 *   <simpleContent>
 *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *       <attribute ref="{urn:solarnetwork:datum:1.0}datum-property use="required""/>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}datum-property-classification default="i""/>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}expression-lang default="net.solarnetwork.common.expr.spel.SpelExpressionService""/>
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyExpression", namespace = "urn:solarnetwork:datum:1.0", propOrder = {
    "value"
})
public class PropertyExpression {

    @XmlValue
    protected String value;
    /**
     * The datum property name to populate for this
     *                             expression.
     * 
     */
    @XmlAttribute(name = "datum-property", namespace = "urn:solarnetwork:datum:1.0", required = true)
    protected String datumProperty;
    /**
     * The datum property classification of the property to
     *                             populate for this expression.
     * 
     */
    @XmlAttribute(name = "datum-property-classification", namespace = "urn:solarnetwork:datum:1.0")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String datumPropertyClassification;
    /**
     * The datum property classification of the property to
     *                             populate for this expression.
     * 
     */
    @XmlAttribute(name = "expression-lang", namespace = "urn:solarnetwork:datum:1.0")
    protected String expressionLang;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * The datum property name to populate for this
     *                             expression.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumProperty() {
        return datumProperty;
    }

    /**
     * Sets the value of the datumProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDatumProperty()
     */
    public void setDatumProperty(String value) {
        this.datumProperty = value;
    }

    /**
     * The datum property classification of the property to
     *                             populate for this expression.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumPropertyClassification() {
        if (datumPropertyClassification == null) {
            return "i";
        } else {
            return datumPropertyClassification;
        }
    }

    /**
     * Sets the value of the datumPropertyClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDatumPropertyClassification()
     */
    public void setDatumPropertyClassification(String value) {
        this.datumPropertyClassification = value;
    }

    /**
     * The datum property classification of the property to
     *                             populate for this expression.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpressionLang() {
        if (expressionLang == null) {
            return "net.solarnetwork.common.expr.spel.SpelExpressionService";
        } else {
            return expressionLang;
        }
    }

    /**
     * Sets the value of the expressionLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getExpressionLang()
     */
    public void setExpressionLang(String value) {
        this.expressionLang = value;
    }

}
