//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.19 at 08:11:34 AM NZDT 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SignalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://kayak.2codeornot2code.org/1.0}SignalType">
 *       &lt;redefine>
 *         &lt;complexType name="SignalType">
 *           &lt;complexContent>
 *             &lt;extension base="{http://kayak.2codeornot2code.org/1.0}BasicSignalType">
 *               &lt;sequence>
 *                 &lt;element name="Notes" type="{http://kayak.2codeornot2code.org/1.0}NotesType" minOccurs="0"/>
 *                 &lt;element name="Consumer" type="{http://kayak.2codeornot2code.org/1.0}ConsumerType" minOccurs="0"/>
 *                 &lt;element name="Value" type="{http://kayak.2codeornot2code.org/1.0}ValueType" minOccurs="0"/>
 *                 &lt;element name="LabelSet" type="{http://kayak.2codeornot2code.org/1.0}LabelSetType" minOccurs="0"/>
 *               &lt;/sequence>
 *             &lt;/extension>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;sequence>
 *         &lt;element name="Name" type="{urn:solarnetwork:datum:1.0}LocalizedName" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}datum-property use="required""/>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}datum-property-classification default="i""/>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}decimal-scale default="-1""/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalType", propOrder = {
    "localizedName"
})
public class SignalType
    extends OriginalSignalType
{

    @XmlElement(name = "Name")
    protected List<LocalizedName> localizedName;
    @XmlAttribute(name = "datum-property", namespace = "urn:solarnetwork:datum:1.0", required = true)
    protected String datumProperty;
    @XmlAttribute(name = "datum-property-classification", namespace = "urn:solarnetwork:datum:1.0")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String datumPropertyClassification;
    @XmlAttribute(name = "decimal-scale", namespace = "urn:solarnetwork:datum:1.0")
    protected Integer decimalScale;

    /**
     * Gets the value of the localizedName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizedName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizedName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedName }
     * 
     * 
     */
    public List<LocalizedName> getLocalizedName() {
        if (localizedName == null) {
            localizedName = new ArrayList<LocalizedName>();
        }
        return this.localizedName;
    }

    /**
     * The datum property name to populate for this
     *                                 signal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumProperty() {
        return datumProperty;
    }

    /**
     * Sets the value of the datumProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumProperty(String value) {
        this.datumProperty = value;
    }

    /**
     * The datum property classification of the property to
     *                                 populate for this signal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumPropertyClassification() {
        if (datumPropertyClassification == null) {
            return "i";
        } else {
            return datumPropertyClassification;
        }
    }

    /**
     * Sets the value of the datumPropertyClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumPropertyClassification(String value) {
        this.datumPropertyClassification = value;
    }

    /**
     * A maximum scale (number of digits after the decimal
     *                                 point) to round decimal values to. This is applied after all
     *                                 transforms. Set to 0 to round to whole numbers. Set to -1 to disable
     *                                 rounding.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDecimalScale() {
        if (decimalScale == null) {
            return -1;
        } else {
            return decimalScale;
        }
    }

    /**
     * Sets the value of the decimalScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDecimalScale(Integer value) {
        this.decimalScale = value;
    }

}
