//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SignalType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="SignalType">
 *   <complexContent>
 *     <extension base="{http://kayak.2codeornot2code.org/1.0}SignalType">
 *       <redefine>
 *         <complexType name="SignalType">
 *           <complexContent>
 *             <extension base="{http://kayak.2codeornot2code.org/1.0}BasicSignalType">
 *               <sequence>
 *                 <element name="Notes" type="{http://kayak.2codeornot2code.org/1.0}NotesType" minOccurs="0"/>
 *                 <element name="Consumer" type="{http://kayak.2codeornot2code.org/1.0}ConsumerType" minOccurs="0"/>
 *                 <element name="Value" type="{http://kayak.2codeornot2code.org/1.0}ValueType" minOccurs="0"/>
 *                 <element name="LabelSet" type="{http://kayak.2codeornot2code.org/1.0}LabelSetType" minOccurs="0"/>
 *               </sequence>
 *             </extension>
 *           </complexContent>
 *         </complexType>
 *       </redefine>
 *       <sequence>
 *         <element name="Name" type="{urn:solarnetwork:datum:1.0}LocalizedName" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}datum-property use="required""/>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}datum-property-classification default="i""/>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}decimal-scale default="-1""/>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalType", propOrder = {
    "localizedName"
})
public class SignalType
    extends OriginalSignalType
{

    /**
     * Localized names of this signal.
     * 
     */
    @XmlElement(name = "Name")
    protected List<LocalizedName> localizedName;
    /**
     * The datum property name to populate for this
     *                                 signal.
     * 
     */
    @XmlAttribute(name = "datum-property", namespace = "urn:solarnetwork:datum:1.0", required = true)
    protected String datumProperty;
    /**
     * The datum property classification of the property to
     *                                 populate for this signal.
     * 
     */
    @XmlAttribute(name = "datum-property-classification", namespace = "urn:solarnetwork:datum:1.0")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String datumPropertyClassification;
    /**
     * A maximum scale (number of digits after the decimal
     *                                 point) to round decimal values to. This is applied after all
     *                                 transforms. Set to 0 to round to whole numbers. Set to -1 to disable
     *                                 rounding.
     * 
     */
    @XmlAttribute(name = "decimal-scale", namespace = "urn:solarnetwork:datum:1.0")
    protected Integer decimalScale;

    /**
     * Localized names of this signal.
     * 
     * Gets the value of the localizedName property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizedName property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLocalizedName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizedName }
     * </p>
     * 
     * 
     * @return
     *     The value of the localizedName property.
     */
    public List<LocalizedName> getLocalizedName() {
        if (localizedName == null) {
            localizedName = new ArrayList<>();
        }
        return this.localizedName;
    }

    /**
     * The datum property name to populate for this
     *                                 signal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumProperty() {
        return datumProperty;
    }

    /**
     * Sets the value of the datumProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDatumProperty()
     */
    public void setDatumProperty(String value) {
        this.datumProperty = value;
    }

    /**
     * The datum property classification of the property to
     *                                 populate for this signal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumPropertyClassification() {
        if (datumPropertyClassification == null) {
            return "i";
        } else {
            return datumPropertyClassification;
        }
    }

    /**
     * Sets the value of the datumPropertyClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDatumPropertyClassification()
     */
    public void setDatumPropertyClassification(String value) {
        this.datumPropertyClassification = value;
    }

    /**
     * A maximum scale (number of digits after the decimal
     *                                 point) to round decimal values to. This is applied after all
     *                                 transforms. Set to 0 to round to whole numbers. Set to -1 to disable
     *                                 rounding.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDecimalScale() {
        if (decimalScale == null) {
            return -1;
        } else {
            return decimalScale;
        }
    }

    /**
     * Sets the value of the decimalScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getDecimalScale()
     */
    public void setDecimalScale(Integer value) {
        this.decimalScale = value;
    }

}
