//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.01 at 10:58:48 AM NZDT 
//


package net.solarnetwork.node.io.canbus.kcd;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SignalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://kayak.2codeornot2code.org/1.0}SignalType">
 *       &lt;redefine>
 *         &lt;complexType name="SignalType">
 *           &lt;complexContent>
 *             &lt;extension base="{http://kayak.2codeornot2code.org/1.0}BasicSignalType">
 *               &lt;sequence>
 *                 &lt;element name="Notes" type="{http://kayak.2codeornot2code.org/1.0}NotesType" minOccurs="0"/>
 *                 &lt;element name="Consumer" type="{http://kayak.2codeornot2code.org/1.0}ConsumerType" minOccurs="0"/>
 *                 &lt;element name="Value" type="{http://kayak.2codeornot2code.org/1.0}ValueType" minOccurs="0"/>
 *                 &lt;element name="LabelSet" type="{http://kayak.2codeornot2code.org/1.0}LabelSetType" minOccurs="0"/>
 *               &lt;/sequence>
 *             &lt;/extension>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}datum-property use="required""/>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}datum-property-classification default="i""/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalType")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class SignalType
    extends OriginalSignalType
{

    @XmlAttribute(name = "datum-property", namespace = "urn:solarnetwork:datum:1.0", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String datumProperty;
    @XmlAttribute(name = "datum-property-classification", namespace = "urn:solarnetwork:datum:1.0")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String datumPropertyClassification;

    /**
     * The datum property name to populate for this
     *                                 signal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getDatumProperty() {
        return datumProperty;
    }

    /**
     * Sets the value of the datumProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDatumProperty(String value) {
        this.datumProperty = value;
    }

    /**
     * The datum property classification of the property to
     *                                 populate for this signal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getDatumPropertyClassification() {
        if (datumPropertyClassification == null) {
            return "i";
        } else {
            return datumPropertyClassification;
        }
    }

    /**
     * Sets the value of the datumPropertyClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2019-10-01T10:58:48+13:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDatumPropertyClassification(String value) {
        this.datumPropertyClassification = value;
    }

}
