//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package net.solarnetwork.node.io.canbus.kcd;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValueType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ValueType">
 *   <complexContent>
 *     <extension base="{http://kayak.2codeornot2code.org/1.0}ValueType">
 *       <redefine>
 *         <complexType name="ValueType">
 *           <complexContent>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               <attribute name="type" default="unsigned">
 *                 <simpleType>
 *                   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                     <enumeration value="unsigned"/>
 *                     <enumeration value="signed"/>
 *                     <enumeration value="single"/>
 *                     <enumeration value="double"/>
 *                   </restriction>
 *                 </simpleType>
 *               </attribute>
 *               <attribute name="slope" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *               <attribute name="intercept" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *               <attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *               <attribute name="min" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *               <attribute name="max" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *             </restriction>
 *           </complexContent>
 *         </complexType>
 *       </redefine>
 *       <attribute ref="{urn:solarnetwork:datum:1.0}normalized-unit"/>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueType")
public class ValueType
    extends OriginalValueType
{

    /**
     * If provided, the desired normalized unit to use. If not
     *                             provided then standard normalization rules will apply.
     * 
     */
    @XmlAttribute(name = "normalized-unit", namespace = "urn:solarnetwork:datum:1.0")
    protected String normalizedUnit;

    /**
     * If provided, the desired normalized unit to use. If not
     *                             provided then standard normalization rules will apply.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedUnit() {
        return normalizedUnit;
    }

    /**
     * Sets the value of the normalizedUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNormalizedUnit()
     */
    public void setNormalizedUnit(String value) {
        this.normalizedUnit = value;
    }

}
