//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.06 at 08:03:13 AM NZST 
//


package net.solarnetwork.node.io.canbus.kcd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValueType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://kayak.2codeornot2code.org/1.0}ValueType">
 *       &lt;redefine>
 *         &lt;complexType name="ValueType">
 *           &lt;complexContent>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;attribute name="type" default="unsigned">
 *                 &lt;simpleType>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                     &lt;enumeration value="unsigned"/>
 *                     &lt;enumeration value="signed"/>
 *                     &lt;enumeration value="single"/>
 *                     &lt;enumeration value="double"/>
 *                   &lt;/restriction>
 *                 &lt;/simpleType>
 *               &lt;/attribute>
 *               &lt;attribute name="slope" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *               &lt;attribute name="intercept" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *               &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *               &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *               &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *             &lt;/restriction>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;attribute ref="{urn:solarnetwork:datum:1.0}normalized-unit"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueType")
public class ValueType
    extends OriginalValueType
{

    @XmlAttribute(name = "normalized-unit", namespace = "urn:solarnetwork:datum:1.0")
    protected String normalizedUnit;

    /**
     * If provided, the desired normalized unit to use. If not
     *                             provided then standard normalization rules will apply.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedUnit() {
        return normalizedUnit;
    }

    /**
     * Sets the value of the normalizedUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedUnit(String value) {
        this.normalizedUnit = value;
    }

}
