title = Fixed Data
desc = Generate datum from static property configurations or a time-of-use (TOU) schedule.

sourceId.key = Source ID
sourceId.desc = The Source ID to use for the generated datum.

datumStatus.key = Latest Datum
datumStatus.desc = An overview of the last-generated datum.

touStatus.key = TOU Status
touStatus.desc = Overview status of the TOU schedule.

rules.empty = No rules.
cached.valid = Schedule cached at {0}; expires at {1}.
cached.invalid = Schedule cached at {0}; expired at {1}.
rates.active = Active rates (calculated at {0}):
schedule.none = No schedule available.

propertyConfigs.key = Property Configurations
propertyConfigs.desc = The list of datum property configurations.

propertyConfigsItem.propertyKey.key = Property
propertyConfigsItem.propertyKey.desc = The datum property name to populate.

propertyConfigsItem.propertyTypeKey.key = Property Type
propertyConfigsItem.propertyTypeKey.desc = The datum property type to use.

propertyConfigsItem.config.key = Property Value
propertyConfigsItem.config.desc = The datum property value to use.

metadataServiceUid.key = Metadata Service
metadataServiceUid.desc = The <b>Service Name</b> of the <i>Metadata Service</i> to obtain TOU schedules from.

touMetadataPath.key = TOU Metadata Path
touMetadataPath.desc = The metadata path that will resolve a TOU schedule from the configured \
	Metadata Service. For example: <code>/pm/rates/energy-rate-schedule</code>.

touLanguage.key = TOU Language
touLanguage.desc = A language to parse the TOU schedule with. If not configured then the system \
	language will be assumed.

touScheduleCacheTtlSecs.key = TOU Schedule Cache
touScheduleCacheTtlSecs.desc = The maximum number of <b>seconds</b> to cache parsed TOU schedule information \
	before reloading from the configured <b>Metadata Service</b>.

touZoneId.key = TOU Zone
touZoneId.desc = The identifier of the time zone used by the TOU schedule, for example \
	<code>Pacific/Auckland</code>. Defaults to the system time zone.

touScaleFactor.key = TOU Scale Factor
touScaleFactor.desc = A multiplication factor to apply to the resolved TOU schedule rates.
