SELECT 
	SYSSCHEMAS.SCHEMANAME, 
	SYSTABS.TABLENAME, 
	MAX(ESTIMSPACESAVING) AS ESTIMSPACESAVING,
	SUM(T2.NUMALLOCATEDPAGES * T2.PAGESIZE) AS DISKSIZE
FROM
    SYS.SYSTABLES SYSTABS, 
    SYS.SYSSCHEMAS SYSSCHEMAS,
    TABLE (SYSCS_DIAG.SPACE_TABLE()) AS T2
WHERE SYSSCHEMAS.SCHEMANAME = 'SOLARNODE'
    AND SYSTABS.TABLETYPE = 'T'
    AND SYSSCHEMAS.SCHEMAID = SYSTABS.SCHEMAID
    AND SYSTABS.TABLEID = T2.TABLEID
GROUP BY SYSSCHEMAS.SCHEMANAME, SYSTABS.TABLENAME
ORDER BY DISKSIZE DESC