/* ==================================================================
 * JdbcDayDatumDao.java - Feb 15, 2011 9:11:34 AM
 * 
 * Copyright 2007-2011 SolarNetwork.net Dev Team
 * 
 * This program is free software; you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation; either version 2 of 
 * the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 
 * 02111-1307 USA
 * ==================================================================
 */

package net.solarnetwork.node.dao.jdbc.weather;

import static net.solarnetwork.node.dao.jdbc.JdbcDaoConstants.SCHEMA_NAME;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import net.solarnetwork.node.DatumUpload;
import net.solarnetwork.node.dao.jdbc.AbstractJdbcDatumDao;
import net.solarnetwork.node.weather.DayDatum;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * JDBC-based implementation of {@link net.solarnetwork.node.dao.DatumDao} for
 * {@link PriceDatum} domain objects.
 * 
 * <p>
 * Uses a {@link javax.sql.DataSource} and requires a schema named
 * {@link net.solarnetwork.node.dao.jdbc.JdbcDaoConstants#SCHEMA_NAME} with two
 * tables:
 * {@link net.solarnetwork.node.dao.jdbc.JdbcDaoConstants#TABLE_SETTINGS} to
 * hold settings and {@link #TABLE_PRICE_DATUM} to hold the actual price data.
 * </p>
 * 
 * <p>
 * This class will check to see if the
 * {@link net.solarnetwork.node.dao.jdbc.JdbcDaoConstants#TABLE_SETTINGS} table
 * exists when the {@link #init()} method is called. If it does not, it assumes
 * the database needs to be created and will load a classpath SQL file resource
 * specified by the {@link #getInitSqlResource()}, which should create the
 * tables needed by this class. See the {@code derby-init.sql} resource in this
 * package for an example.
 * </p>
 * 
 * <p>
 * The tables must have a structure similar to this (shown in Apache Derby SQL
 * dialect):
 * </p>
 * 
 * <pre>
 * CREATE TABLE solarnode.sn_settings (
 * 	skey	VARCHAR(64) NOT NULL,
 * 	svalue	VARCHAR(255) NOT NULL,
 * 	PRIMARY KEY (skey)
 * 	)
 * 	
 * CREATE TABLE solarnode.sn_price_datum (
 * 	id				BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 * 	created			TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
 * 	source_id 		VARCHAR(255),
 * 	tz				VARCHAR(255) NOT NULL,
 * 	latitude		DOUBLE,
 * 	longitude		DOUBLE,
 * 	sunrise			TIME,
 * 	sunset			TIME
 * 	PRIMARY KEY (id)
 * )
 * </pre>
 * 
 * @author matt
 * @version 1.1
 */
public class JdbcDayDatumDao extends AbstractJdbcDatumDao<DayDatum> {

	/** The default tables version. */
	public static final int DEFAULT_TABLES_VERSION = 2;

	/** The table name for {@link DayDatum} data. */
	public static final String TABLE_DAY_DATUM = "sn_day_datum";

	/** The table name for DayDatum upload data. */
	public static final String TABLE_DAY_DATUM_UPLOAD = "sn_day_datum_upload";

	/** The default classpath Resource for the {@code initSqlResource}. */
	public static final String DEFAULT_INIT_SQL = "derby-daydatum-init.sql";

	private static final String DEFAULT_SQL_INSERT = "INSERT INTO " + SCHEMA_NAME + '.'
			+ TABLE_DAY_DATUM + " (source_id, tz, latitude, longitude, sunrise, sunset) VALUES"
			+ " (?,?,?,?,?,?)";

	/** The default value for the {@code sqlGetTablesVersion} property. */
	public static final String DEFAULT_SQL_GET_TABLES_VERSION = "SELECT svalue FROM solarnode.sn_settings WHERE skey = "
			+ "'solarnode.sn_day_datum.version'";

	/** The default classpath Resource for the {@code findForUploadSqlResource}. */
	public static final String DEFAULT_FIND_FOR_UPLOAD_SQL = "find-day-for-upload.sql";

	private static final String DEFAULT_SQL_INSERT_UPLOAD = "INSERT INTO " + SCHEMA_NAME + '.'
			+ TABLE_DAY_DATUM_UPLOAD + " (datum_id, destination, track_id) VALUES (?,?,?)";

	private static final String DEFAULT_SQL_DELETE_OLD = "DELETE FROM " + SCHEMA_NAME + '.'
			+ TABLE_DAY_DATUM + " where id <= (select MAX(cd.id) from " + SCHEMA_NAME + '.'
			+ TABLE_DAY_DATUM + " cd inner join " + SCHEMA_NAME + '.' + TABLE_DAY_DATUM_UPLOAD
			+ " u on u.datum_id = cd.id where cd.created < ?)";

	/**
	 * Default constructor.
	 */
	public JdbcDayDatumDao() {
		super();
		setTableName(TABLE_DAY_DATUM);
		setUploadTableName(TABLE_DAY_DATUM_UPLOAD);
		setTablesVersion(DEFAULT_TABLES_VERSION);
		setSqlGetTablesVersion(DEFAULT_SQL_GET_TABLES_VERSION);
		setSqlResourcePrefix("derby-pricedatum");
		setInitSqlResource(new ClassPathResource(DEFAULT_INIT_SQL, getClass()));
		setSqlDeleteOld(DEFAULT_SQL_DELETE_OLD);
		setFindForUploadSqlResource(new ClassPathResource(DEFAULT_FIND_FOR_UPLOAD_SQL, getClass()));
		setSqlInsertDatum(DEFAULT_SQL_INSERT);
		setSqlInsertUpload(DEFAULT_SQL_INSERT_UPLOAD);
	}

	@Override
	public Class<? extends DayDatum> getDatumType() {
		return DayDatum.class;
	}

	@Override
	@Transactional(readOnly = false, propagation = Propagation.REQUIRED)
	public Long storeDatum(DayDatum datum) {
		return storeDomainObject(datum);
	}

	@Override
	@Transactional(readOnly = true, propagation = Propagation.REQUIRED)
	public List<DayDatum> getDatumNotUploaded(String destination) {
		return findDatumNotUploaded(destination, new RowMapper<DayDatum>() {

			@Override
			public DayDatum mapRow(ResultSet rs, int rowNum) throws SQLException {
				if ( log.isTraceEnabled() ) {
					log.trace("Handling result row " + rowNum);
				}
				DayDatum datum = new DayDatum();
				int col = 1;
				datum.setId(rs.getLong(col++));
				datum.setCreated(rs.getTimestamp(col++));
				datum.setSourceId(rs.getString(col++));
				datum.setTimeZoneId(rs.getString(col++));

				Number val = (Number) rs.getObject(col++);
				datum.setLatitude(val == null ? null : val.doubleValue());

				val = (Number) rs.getObject(col++);
				datum.setLongitude(val == null ? null : val.doubleValue());

				datum.setSunrise(rs.getTime(col++));
				datum.setSunset(rs.getTime(col++));

				return datum;
			}
		});
	}

	@Override
	@Transactional(readOnly = false, propagation = Propagation.REQUIRED)
	public DatumUpload storeDatumUpload(DayDatum datum, String destination, Long trackingId) {
		return storeNewDatumUpload(datum, destination, trackingId);
	}

	@Override
	@Transactional(readOnly = false, propagation = Propagation.REQUIRED)
	public int deleteUploadedDataOlderThan(int hours) {
		return deleteUploadedDataOlderThanHours(hours);
	}

	@Override
	protected void setStoreStatementValues(DayDatum datum, PreparedStatement ps) throws SQLException {
		int col = 1;
		ps.setString(col++, datum.getSourceId());
		if ( datum.getTimeZoneId() == null ) {
			ps.setNull(col++, Types.VARCHAR);
		} else {
			ps.setString(col++, datum.getTimeZoneId());
		}
		if ( datum.getLatitude() == null ) {
			ps.setNull(col++, Types.DOUBLE);
		} else {
			ps.setDouble(col++, datum.getLatitude());
		}
		if ( datum.getLongitude() == null ) {
			ps.setNull(col++, Types.DOUBLE);
		} else {
			ps.setDouble(col++, datum.getLongitude());
		}
		if ( datum.getSunrise() == null ) {
			ps.setNull(col++, Types.TIME);
		} else {
			ps.setTime(col++, new java.sql.Time(datum.getSunrise().getTime()));
		}
		if ( datum.getSunset() == null ) {
			ps.setNull(col++, Types.TIME);
		} else {
			ps.setTime(col++, new java.sql.Time(datum.getSunset().getTime()));
		}
	}
}
