title = Tesla Powerwall
desc = Collect data from Tesla Powerwall devices. This plugin will generate up to four datum streams, \
	using the configured Source ID as the basis for the different components of the Tesla system: \
	<b>battery</b>, <b>load</b>, <b>site</b>, and \ <b>solar</b>.

sourceId.key = Source ID
sourceId.desc = A unique source identifier. Configure a <code>{COMP}</code> placeholder \
	to substitute the <b>Battery</b>, <b>Load</b>, <b>Site</b>, and <b>Solar</b> Placeholder values \
	in the source IDs resolved for each component datum stream.

hostName.key = Host Name
hostName.desc = The host name of the Powerwall to connect to. A non-standard IP port can \
	be included with a <code>:</code> delimiter, for example <code>powerwall:9999</code>.

username.key = Username
username.desc = The Powerwall username to connect with. Can use <code>customer</code> along \
	with a password set to the last 5 characters of the Powerwall serial number.

password.key = Password
password.desc = The Powerwall password to connect with. If the <b>Username</b> is set to \
	<code>customer</code> then the password is the last 5 characters of the Powerwall serial number.

batteryPlaceholder.key = Battery Placeholder
batteryPlaceholder.desc = The component for battery data.

loadPlaceholder.key = Load Placeholder
loadPlaceholder.desc = The component for load (consumption from the grid) data.

sitePlaceholder.key = Site Placeholder
sitePlaceholder.desc = The component for overall site data.

solarPlaceholder.key = Solar Placeholder
solarPlaceholder.desc = The component for solar generation data.
