101 = net.solarnetwork.node.hw.sunspec.inverter.IntegerInverterModelAccessor
102 = net.solarnetwork.node.hw.sunspec.inverter.IntegerInverterModelAccessor
103 = net.solarnetwork.node.hw.sunspec.inverter.IntegerInverterModelAccessor

111 = net.solarnetwork.node.hw.sunspec.inverter.FloatingPointInverterModelAccessor
112 = net.solarnetwork.node.hw.sunspec.inverter.FloatingPointInverterModelAccessor
113 = net.solarnetwork.node.hw.sunspec.inverter.FloatingPointInverterModelAccessor

120 = net.solarnetwork.node.hw.sunspec.inverter.InverterNameplateRatingsModelAccessorImpl
121 = net.solarnetwork.node.hw.sunspec.inverter.InverterBasicSettingsModelAccessorImpl

160 = net.solarnetwork.node.hw.sunspec.inverter.InverterMpptExtensionModelAccessorImpl

201 = net.solarnetwork.node.hw.sunspec.meter.IntegerMeterModelAccessor
202 = net.solarnetwork.node.hw.sunspec.meter.IntegerMeterModelAccessor
203 = net.solarnetwork.node.hw.sunspec.meter.IntegerMeterModelAccessor
204 = net.solarnetwork.node.hw.sunspec.meter.IntegerMeterModelAccessor

211 = net.solarnetwork.node.hw.sunspec.meter.IntegerMeterModelAccessor
212 = net.solarnetwork.node.hw.sunspec.meter.IntegerMeterModelAccessor
213 = net.solarnetwork.node.hw.sunspec.meter.IntegerMeterModelAccessor
214 = net.solarnetwork.node.hw.sunspec.meter.IntegerMeterModelAccessor

302 = net.solarnetwork.node.hw.sunspec.environmental.IrradianceModelAccessorImpl
303 = net.solarnetwork.node.hw.sunspec.environmental.BomTemperatureModelAccessorImpl
304 = net.solarnetwork.node.hw.sunspec.environmental.InclinometerModelAccessorImpl
305 = net.solarnetwork.node.hw.sunspec.environmental.GpsModelAccessorImpl
306 = net.solarnetwork.node.hw.sunspec.environmental.ReferencePointModelAccessorImpl
307 = net.solarnetwork.node.hw.sunspec.environmental.MeteorologicalModelAccessorImpl
308 = net.solarnetwork.node.hw.sunspec.environmental.MiniMeteorologicalModelAccessorImpl

401 = net.solarnetwork.node.hw.sunspec.combiner.StringCombinerModelAccessorImpl
402 = net.solarnetwork.node.hw.sunspec.combiner.StringCombinerAdvancedModelAccessorImpl
403 = net.solarnetwork.node.hw.sunspec.combiner.StringCombinerModelAccessorImpl
404 = net.solarnetwork.node.hw.sunspec.combiner.StringCombinerAdvancedModelAccessorImpl

701 = net.solarnetwork.node.hw.sunspec.der.DerAcMeasurementModelAccessorImpl
702 = net.solarnetwork.node.hw.sunspec.der.DerCapacityModelAccessorImpl
703 = net.solarnetwork.node.hw.sunspec.der.DerEnterServiceModelAccessorImpl
704 = net.solarnetwork.node.hw.sunspec.der.DerAcControlsModelAccessorImpl
705 = net.solarnetwork.node.hw.sunspec.der.DerVoltVarModelAccessorImpl
706 = net.solarnetwork.node.hw.sunspec.der.DerVoltWattModelAccessorImpl
707 = net.solarnetwork.node.hw.sunspec.der.DerTripLowVoltageModelAccessorImpl
708 = net.solarnetwork.node.hw.sunspec.der.DerTripHighVoltageModelAccessorImpl
709 = net.solarnetwork.node.hw.sunspec.der.DerTripLowFrequencyModelAccessorImpl
710 = net.solarnetwork.node.hw.sunspec.der.DerTripHighFrequencyModelAccessorImpl
711 = net.solarnetwork.node.hw.sunspec.der.DerFrequencyDroopModelAccessorImpl
712 = net.solarnetwork.node.hw.sunspec.der.DerWattVarModelAccessorImpl
713 = net.solarnetwork.node.hw.sunspec.der.DerStorageCapacityModelAccessorImpl
714 = net.solarnetwork.node.hw.sunspec.der.DerDcMeasurementModelAccessorImpl
715 = net.solarnetwork.node.hw.sunspec.der.DerControlModelAccessorImpl
