title = Rounded Timestamp Datum Filter
desc = This component provides a way to round datum timestamps down to clock-aligned values.

durationMs.key = Duration
durationMs.desc = A duration in milliseconds to round datum timestamps by.
